# Your client credentials (Using github secrets)
client_id: ppf-local
client_key: ppf-local

# The Tapis base URL and tenant id
tapis_base_url: https://icicleai.tapis.io
tenant: icicleai

# The base URL that you app isserved on; this needs to match what was registered with the  OAuth client
#the catalog to a public URL. 
app_base_url: https://digital-agriculture-sandbox-frontend-1:3000

callback_url: http://localhost:5003/api/oauth2/callback

description: Auth Client for local development of PPF

display_name: PPF-Local

